name: Publish docs to gh-pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo doc --no-deps
      - name: Prepare
        run: ./utils/prepare-docs-for-gh-pages.sh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
